
#--- Kapu ---
- label:
    x: 5
    y: 26
    width: 70
    text: "Kapu"
    styles: idStylePageBack
    text_align: CENTER
- button:
    x: 5
    y: 50
    width: 70
    height: 55
    styles: idStyleButtons    
    widgets:
      - label:
          id: idBKapuStart
          align: CENTER
          text: "Start"
    on_press:
      then:
        - homeassistant.action:
            action: button.press
            data:
              entity_id: button.ookcontrol_kapu_start
- button:
    x: 5
    y: 115
    width: 70
    height: 55
    styles: idStyleButtons    
    widgets:
      - label:
          id: idBKapuStop
          align: CENTER
          text: STOP
    on_press:
      then:
        - homeassistant.action:
            action: button.press
            data:
              entity_id: button.ookcontrol_kapu_stop
- button:
    x: 5
    y: 180
    width: 70
    height: 55
    styles: idStyleButtons    
    widgets:
      - label:
          id: idBKapuSzemelyi
          align: CENTER
          text: "Szemelyi"
    on_press:
      then:
        - homeassistant.action:
            action: button.press
            data:
              entity_id: button.ookcontrol_kapu_szem_lyi

#---[ Gar√°zs ]---
- label:
    x: 90
    y: 89
    width: 140
    text: "Garazskapu"
    text_align: CENTER
    styles: idStylePageBack    
- button:
    x: 90
    y: 115
    width: 140
    height: 55
    styles: idStyleButtons
    widgets:
      - label:
          id: idBGarazsKapuLabel
          align: CENTER
          text: "Garazsgomb"
    on_press:
      then:
        - homeassistant.action:
            action: button.press
            data:
              entity_id: button.ookcontrol_gar_zskapu



