- id: idStyleFooter
  bg_color: 0x2F8CD8
  bg_grad_color: 0x2F8CD8
  bg_grad_dir: VER
  bg_opa: COVER
  border_opa: TRANSP
  radius: 0
  pad_all: 0
  pad_row: 0
  pad_column: 0
  border_color: 0x0077b3
  text_color: 0xFFFFFF
  width: 100%
  height: 65

- id: header
  bg_color: 0x009900
  bg_grad_color: 0x004400
  bg_grad_dir: VER
  bg_opa: COVER
  border_opa: TRANSP
  radius: 0
  pad_all: 0
  pad_row: 0
  pad_column: 0
  border_color: 0x0077b3
  text_color: 0xFFFFFF
  width: 100%
  height: 18

- id: idStyleButtons
  bg_color: 0x0000FF
  bg_grad_color: 0x0000FF
  bg_grad_dir: VER
  bg_opa: COVER
  border_opa: TRANSP
  radius: 6
  pad_all: 0
  pad_row: 0
  pad_column: 0
  border_color: 0x000055
  text_color: 0xFFFFFF
  width: 100%
  height: 18

- id: idStylePageBack
  bg_color: 0x000000
  bg_grad_color: 0x000000
  bg_grad_dir: VER
  bg_opa: COVER
  border_opa: TRANSP
  radius: 0
  pad_all: 0
  pad_row: 0
  pad_column: 0
  border_color: 0x0077b3
  text_color: 0xFFFFFF
  width: 100%
  height: 18  